#
# This is a simple awk program which will generate defaultstring.c
# from an X resource file.
#

#
# insert the "header" for defaultstring.c
#
BEGIN {
  print "/*";
  print " * Do not edit this file.";
  print " * This file is generated automagically from Xdefaults";
  print " * using the awk program found in defresources.awk.";
  print " * This file will be rebuilt when Xdefaults is modified.";
  print " */\n";
  print "const char *defaultXResourceString =";
}

#
# Echo each line of input (that is not a comment or empty) to stdout as its
# own string literal.  Adjacent literals concatenate, and keeping each one on
# its own line stays under the line length a C89 compiler has to support.
#
(! /^!/) && (NF != 0) { printf "\"%s\\n\"\n", $0 }

#
# Insert the "tail" for defaultstring.c
#
END {
  print ";";
}
